//
//  DatabaseVenue.swift
//  Club Ralley
//
//  Codable model matching the Supabase venues table
//

import Foundation

struct DatabaseVenue: Codable {
    let id: UUID
    let name: String
    let address: String
    let city: String
    let state: String
    let type: String
    let latitude: Decimal
    let longitude: Decimal
    let sports: [String]
    let is_active: Bool
    let source: String?
    let osm_id: String?
    let last_fetched_at: String?
}

/// Insert-only model (no `id` — auto-generated by Supabase)
struct DatabaseVenueInsert: Codable {
    let name: String
    let address: String
    let city: String
    let state: String
    let type: String
    let latitude: Decimal
    let longitude: Decimal
    let sports: [String]
    let is_active: Bool
    let source: String
    let osm_id: String?
    let last_fetched_at: String
}
